### ISSUE TITLE
[META] UX for Dynamic tenancy configuration in OpenSearch Dashboards Security Plugin

### ISSUE THREAD

**Issue by shanilpa** [opensearch-project/security-dashboards-plugin#1319]
## Context
This is a meta issue for UX work/tasks related to [this issue](https://github.com/opensearch-project/security-dashboards-plugin/issues/1302#issuecomment-1416653794) and [this RFC](https://github.com/opensearch-project/OpenSearch/issues/5853) for making tenancy configurable in OpenSearch Dashboards.

**Users / Personas**
- Admin - This is a user that has access to the security plugin and can configure tenancy. They can also use tenancy like a non-admin user would.
- Non-admin - These are users that do not have access to the security plugin, they can not configure tenancy but can use the feature if it is enabled and their admin has granted them appropriate permissions to do so.

## UX Scope
The scope of this UX work focuses around these high level use cases:
- [ ] [Enable / disable the private tenant through UI in OpenSearch Dashboards Security Plugin ](https://github.com/opensearch-project/security-dashboards-plugin/issues/1317)
- [ ] [Set a default tenant (global or private) through UI in OpenSearch Dashboards Security Plugin](https://github.com/opensearch-project/security-dashboards-plugin/issues/1318)
- [ ] [Enable / disable tenancy through UI in OpenSearch Dashboards Security Plugin](https://github.com/opensearch-project/security-dashboards-plugin/issues/1316)

**Comment by kgcreative** [comment]
References: 
* https://github.com/opensearch-project/security-dashboards-plugin/issues/1317
* https://github.com/opensearch-project/OpenSearch/issues/5853

**Comment by shanilpa** [comment]
Proposed UX for tenancy permissions in other parts of the security plugin as a result of this work: https://github.com/opensearch-project/ux/issues/67

**Comment by shanilpa** [comment]
Feature launched: https://github.com/opensearch-project/security/pull/2607
